### ISSUE TITLE
Add Log class

### ISSUE THREAD

**Issue by Makman2** [coala-analyzer/PyPrint#17]
A Log class is a simple list of log entries where logging functions are wrapped around.

This class has following capabilities:
- Functions for logging with different log-levels
- Stores logged messages
- Log-levels are not adjustable, maybe we just use **INFO**, **DEBUG**, **ERROR** (or more)
- Can hold printers where log messages are immediately printed to
- Contains properties/functions that define print behaviour to the underlying printers
- Has filters to suppress output of different log-levels
- ...

**Comment by sils1297** [comment]
we wouldn't want that, we'd rather go for python builtin logging support.
