### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/PyPrint#2]
@sils1297 I dont have access to add this to scrutinizer nor appveyor nor circleci :)

Could you enable all of them ? (And add secret keys also)

**Comment by sils1297** [comment]
sure, what secret keys do you need?

**Comment by sils1297** [comment]
Why circleci? I'd say using travis for linux and mac is easier with the build matrix. We can let tox take care of doing all the virtualenv stuff.

**Comment by sils1297** [comment]
@AbdealiJK I activated scrutinizer, circle and appveyor
