### ISSUE TITLE
ConsolePrinter : Fails to initialize colorama 

### ISSUE THREAD

**Issue by abhsag24** [coala-analyzer/PyPrint#23]
The test for coalaTest fail in coala-analyzer/coala giving traceback as
http://pastebin.com/AC3u0Pk7 (ending of tests)

and
```
  14/116 | coalaTest
test_fail_acquire_settings (__main__.coalaTest) ... ok
test_find_issues (__main__.coalaTest) ... ok
test_find_no_issues (__main__.coalaTest) ... FAIL
test_nonexistent (__main__.coalaTest) ... ERROR
test_tagging (__main__.coalaTest) ... ERROR

======================================================================
ERROR: test_nonexistent (__main__.coalaTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/coala/coalib/tests/coalaTest.py", line 47, in test_nonexistent
    retval, output = execute_coala_ci(("-c", "nonex", "test"))
  File "/home/ubuntu/coala/coalib/tests/coalaTest.py", line 32, in execute_coala_ci
    retval = coala_ci.main()
  File "./coalib/coala_ci.py", line 20, in main
    print_results=print_results_no_input)
  File "./coalib/coala_main.py", line 60, in run_coala
    log_printer = log_printer or LogPrinter(ConsolePrinter())
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/site-packages/pyprint/ConsolePrinter.py", line 22, in __init__
    colorama.init()
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/site-packages/colorama/initialise.py", line 42, in init
    wrap_stream(orig_stderr, convert, strip, autoreset, wrap)
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/site-packages/colorama/initialise.py", line 76, in wrap_stream
    convert=convert, strip=strip, autoreset=autoreset)
  File "/home/ubuntu/.pyenv/versions/3.4.3/lib/python3.4/site-packages/colorama/ansitowin32.py", line 67, in __init__
    strip = conversion_supported or (not wrapped.closed and not is_a_tty(wrapped))
```

as start (from circle-ci)

**Comment by abhsag24** [comment]
Full test at  https://circleci.com/gh/coala-analyzer/coala/3744

**Comment by sils1297** [comment]
@abhsag24 didn't you say you had a minimal example to reproduce the issue?

**Comment by abhsag24** [comment]
@sils1297   I tried to make a more  minimal example but the bug seems to vanish when i take it out of coala? maybe its a bug there ?  , ok so i made file named coala_orig.py which deletes orig files, which has the content 
```
import os
from pyprint.ConsolePrinter import ConsolePrinter

from glob import glob
from coalib.output.printers.LOG_LEVEL import LOG_LEVEL
from coalib.output.printers.LogPrinter import LogPrinter

PATH = os.getcwd()


def main():

    log_printer = LogPrinter(ConsolePrinter())
    orig_files = [y for x in os.walk(PATH)
                  for y in glob(os.path.join(x[0], '*.orig'))]

    for ofile in orig_files:
        try:
            log_printer.log(LOG_LEVEL.DEBUG, "Deleting.." + ofile)
            os.remove(ofile)
        except:
            return 1

    return 0
```
and call this function inside coala_main as ` oret = coala_orig.main()` which seems to work fine independently but fails inside coalaTest.py  with the same error as above (involving colorama) , i know i should try to reproduce this bug independently but this is as far as i could get, i suspect this is because the number of calls to `ConsolePrinter` is very high in the test? can't say for sure

**Comment by AbdealiJK** [comment]
Just thinking out loud here:
(Because you mentioned that something works fine outside but throws errors inside coalaTest.py)

coalaTest works inside a `with retrieve_stdout() as stdout:` - which would mean that the `stdout` is replaced with a `StringIO` - which may not have the same properties like a normal stdout ?

colorama must be checking something here ? this may be causing the error ? (example: maybe colorama assumes that output for something is X or Y but StringIO gives None?)

**Comment by sils1297** [comment]
Good theory, at least running `coala-ci` from that branch outside the tests works well.

**Comment by abhsag24** [comment]
was able to take the error out of the coalaTest environment, maybe this can help?
```
from coalib import coala_ci

def execute_coala_ci(args):
    
    sys.argv = ["coala-ci"] + list(args)
    importlib.reload(ConfigurationGathering)
    importlib.reload(coala_ci)
    with retrieve_stdout() as stdout:
        retval = coala_ci.main()
        print(stdout.getvalue())
        return retval, stdout.getvalue()

ret,output = execute_coala_ci(("-c","/home/abhay/Project/coala/","-L","DEBUG"))
print(output)
```
produces http://pastebin.com/ERsPTf4D

while 
```
def execute_coala_ci(args):
    
    sys.argv = ["coala-ci"] + list(args)
    importlib.reload(ConfigurationGathering)
    importlib.reload(coala_ci)
    retval = coala_ci.main()
    return retval

execute_coala_ci(("-c","/home/abhay/Project/coala/","-L","DEBUG"))
```
produces no errors and a normal output which is: http://pastebin.com/H2dUmRrn

**Comment by sils1297** [comment]
probably related https://github.com/tartley/colorama/issues/83 , so we probably should try to call init once only.

@AbdealiJK @abhsag24 does anyone have time to do this? We could do a static class variable `initialized=False` and we only call init the first time?

**Comment by sils1297** [comment]
as this is kind of global?

**Comment by AbdealiJK** [comment]
Assigning myself
