### ISSUE TITLE
Adding utf-8 encoding to all source files in PyPrint package

### ISSUE THREAD

**Issue by prodicus** [coala-analyzer/PyPrint#29]
Hey guys, 

I saw that the source code encoding is missing in files inside the PyPrint package. I will add them in order to conform to [pep-0263](https://www.python.org/dev/peps/pep-0263/).

**Comment by sils1297** [comment]
phew is this needed? I hate boilerplate code, AFAIK it's only relevant for python 2.

CC @AbdealiJK

**Comment by AbdealiJK** [comment]
I did a bit of checking myself.
@sils1297 is pyprint python2 and py3 compatible ?
If its for py2 - then we should add it.
For py3, apparently utf8 is default, so its not needed i think

Also, the `/usr/bin/python` in the commit is not needed - none of the files are executable - it's a library

**Comment by sils1297** [comment]
we have not made any effort on making it python 2 compatible but possibly it could be if it's of value to others, sure

**Comment by prodicus** [comment]
@sils1297 @AbdealiJK Should I close it then?

**Comment by AbdealiJK** [comment]
@prodicus can you possibly run the tests using `pytest` in python2 ?
If it works then we can simply add the utf stuff so that we support py2 and py3 ?
@sils1297 is that fine ? ( I'm not maintaining pyprint :P )

We can also add py2 to the CI builds

**Comment by sils1297** [comment]
yeah it's totally fine

Sincerely,

Lasse Schuirmann

contact@viperdev.io
http://viperdev.io/

2016-02-29 14:25 GMT+01:00 AbdealiJK <notifications@github.com>:
