### ISSUE TITLE
Add newlines to long lines

### ISSUE THREAD

**Issue by AbdealiJK** [coala-analyzer/PyPrint#31]
In coala it was proposed that there be a newline character added at the end of a line in some cases. Possibly gives better readability.
https://github.com/coala-analyzer/coala/issues/1708
So, we want an arg that will enable auto breaking a line if it's too long. Ideally we would want it to be smart and use the terminal size to do this.

**Comment by Makman2** [comment]
The terminal does auto-breaking, why we should manually catch that? Especially the new bash shell also allows then to re-fit your content when you resize the terminal windows, I don't wanna loose that^^

**Comment by AbdealiJK** [comment]
I think that depends on which terminal

-----Original Message-----

**Comment by Makman2** [comment]
yeah but all modern terminals I've seen do that (the defaults for Ubuntu, fedora, arch, windows (cmd and powershell), centos, raspbian, ...). Imo not in our scope^^

**Comment by AbdealiJK** [comment]
My gnome-terminal doesn't seem to do it :o

But I agree that's it should be a terminal level setting and not an
application level setting. I've just moved the ticket as @abhsag24 and
@sils1297 wanted it in the previous issue
